# Generated by Django 5.1.1 on 2024-10-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardioExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of session')),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.IntegerField(default=8)),
                ('notes', models.CharField(max_length=1000)),
                ('resist_ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_entry.resistanceexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_entry.session')),
            ],
        ),
        migrations.CreateModel(
            name='CardioActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DurationField()),
                ('resistance', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=1000)),
                ('cardio_ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_entry.cardioexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_entry.session')),
            ],
        ),
    ]
