# Generated by Django 5.1.1 on 2024-10-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cardioactivity',
            table='CardioActivity',
        ),
        migrations.AlterModelTable(
            name='cardioexercise',
            table='CardioExercise',
        ),
        migrations.AlterModelTable(
            name='resistanceexercise',
            table='ResistanceExercise',
        ),
        migrations.AlterModelTable(
            name='resistanceset',
            table='ResistanceSet',
        ),
        migrations.AlterModelTable(
            name='session',
            table='Session',
        ),
    ]
