# Generated by Django 5.1.1 on 2024-10-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_entry', '0002_alter_cardioactivity_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cardioactivity',
            table='cardio_activity',
        ),
        migrations.AlterModelTable(
            name='cardioexercise',
            table='cardio_exercise',
        ),
        migrations.AlterModelTable(
            name='resistanceexercise',
            table='resistance_exercise',
        ),
        migrations.AlterModelTable(
            name='resistanceset',
            table='resistance_set',
        ),
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
    ]
